# Form implementation generated from reading ui file 'adbtool.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 405)
        MainWindow.setMinimumSize(QtCore.QSize(550, 405))
        MainWindow.setMaximumSize(QtCore.QSize(550, 405))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.SearchBtn = QtWidgets.QPushButton(parent=self.tab)
        self.SearchBtn.setEnabled(True)
        self.SearchBtn.setGeometry(QtCore.QRect(10, 10, 131, 26))
        self.SearchBtn.setObjectName("SearchBtn")
        self.StatusConn = QtWidgets.QLabel(parent=self.tab)
        self.StatusConn.setGeometry(QtCore.QRect(150, 10, 141, 18))
        self.StatusConn.setObjectName("StatusConn")
        self.RebootBtn = QtWidgets.QPushButton(parent=self.tab)
        self.RebootBtn.setEnabled(False)
        self.RebootBtn.setGeometry(QtCore.QRect(10, 40, 131, 31))
        self.RebootBtn.setObjectName("RebootBtn")
        self.SelectorTypeReboot = QtWidgets.QComboBox(parent=self.tab)
        self.SelectorTypeReboot.setEnabled(False)
        self.SelectorTypeReboot.setGeometry(QtCore.QRect(150, 40, 111, 31))
        self.SelectorTypeReboot.setEditable(False)
        self.SelectorTypeReboot.setObjectName("SelectorTypeReboot")
        self.SelectorTypeReboot.addItem("")
        self.SelectorTypeReboot.addItem("")
        self.SelectorTypeReboot.addItem("")
        self.SelectorTypeReboot.addItem("")
        self.InstallBtn = QtWidgets.QPushButton(parent=self.tab)
        self.InstallBtn.setEnabled(False)
        self.InstallBtn.setGeometry(QtCore.QRect(10, 80, 131, 31))
        self.InstallBtn.setObjectName("InstallBtn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchBtn.setText(_translate("MainWindow", "Найти устройство"))
        self.StatusConn.setText(_translate("MainWindow", "ОТКЛЮЧЕНО"))
        self.RebootBtn.setText(_translate("MainWindow", "Перезагрузить"))
        self.SelectorTypeReboot.setItemText(0, _translate("MainWindow", "Система"))
        self.SelectorTypeReboot.setItemText(1, _translate("MainWindow", "bootloader"))
        self.SelectorTypeReboot.setItemText(2, _translate("MainWindow", "fastboot"))
        self.SelectorTypeReboot.setItemText(3, _translate("MainWindow", "recovery"))
        self.InstallBtn.setText(_translate("MainWindow", "Установить APK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ADB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
